### ISSUE TITLE
Avatars are generated, not displaying

### ISSUE THREAD

**Issue by Tc-001** [Findus23/plugin-ProfileAvatar#1]
Hello!

After installing this plugin on my matomo 4.1.1 machine, I was unable to see the custom avatars.
I attempted clearing the cache, and it did not help.

I can see an avatar when visiting
`http://example.com/matomo/index.php?module=ProfileAvatar&action=getProfileAvatar&hash=aaaaa`
so I know that it is generating them, only not displaying.
Here is what the inspect element has (both with and wihout data URLs):
```html
<div class="visitor-profile-avatar">
    <img src="plugins/Live/images/unknown_avatar.png" alt="" title="">
</div>
```
Poking around with it, I could not find any trace of it attempting to generate the image.

Going through this code I also could not find anything obvious that could cause this, so I posted the issue.
It could be that I need to refresh some of the other plugins, or restart the machine. But because I am running this on a shared server with only ftp access, I am unsure if (or how) I can do that. 

![image](https://user-images.githubusercontent.com/55956895/107886941-92042280-6f0b-11eb-9262-8850c978a9cf.png)

**Comment by Findus23** [comment]
Hi,

I never noticed it, but indeed the plugin also doesn't work for me anymore. I'll look into it

**Comment by Findus23** [comment]
It turns out the function I used has been removed in Matomo 4 and I totally missed that (https://github.com/matomo-org/matomo/pull/15866)

It should be fixed with https://github.com/Findus23/plugin-ProfileAvatar/commit/2b563c4cca5bcc0e49329dfa7a78f275499d6b4a and I'll release an update soon.

**Comment by Findus23** [comment]
0.1.3 with this fix and a new optional feature to display the avatar in the visitor log (https://github.com/Findus23/plugin-ProfileAvatar/commit/6a43cc2bc337c63eaed132e1fb0cf31909460dc5) should be released now

**Comment by Tc-001** [comment]
The avatars generate correctly, but it now shows the following warning in the administration panel

> WARNING: /path/to/matomo/plugins/ProfileAvatar/Generators/MonsterIDBase.php(27): Warning - imagedestroy(): supplied resource is not a valid Image resource - Matomo 4.1.1 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: API, Action: getVisitorProfilePopup, Method: Live.getVisitorProfile, In CLI mode: false)

I am currently using the cat avatar option (not monsterid), and there are no warnings that reference other generators. It seems to create one warning each time an avatar is generated. 

I can't dig deeper sadly, as have to go to bed but will see if I can help tomorrow.

**Comment by Findus23** [comment]
Hi,

Do you by chance use PHP 8?

**Comment by Tc-001** [comment]
Opened #2 right at the same time, can continue here or there

**Comment by Tc-001** [comment]
My php version is 7.2

**Comment by Findus23** [comment]
okay, I'll look into it in #2
