### ISSUE TITLE
Warning in admin panel after avatar generation

### ISSUE THREAD

**Issue by Tc-001** [Findus23/plugin-ProfileAvatar#2]
The fllowing warning appears in the admininistration panel after an avatar gets generated:
> WARNING: /path/to/matomo/plugins/ProfileAvatar/Generators/MonsterIDBase.php(27): Warning - imagedestroy(): supplied resource is not a valid Image resource - Matomo 4.1.1 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: API, Action: getVisitorProfilePopup, Method: Live.getVisitorProfile, In CLI mode: false)

![image](https://user-images.githubusercontent.com/55956895/107925062-94529500-6f7c-11eb-99ce-17cc7562cf9c.png)

I am currently using the cat avatar option (not monsterid), and there are no warnings that reference other generators. It seems to create one warning each time an avatar is generated.

From a quick read it seems that the error is this line: https://github.com/Findus23/plugin-ProfileAvatar/blob/050afdd6e1e4076d54e4bc09bc882ec96ef83a5b/Generators/MonsterIDBase.php#L27
I am unsure if this was a problem before the plugin update, as the git blame puts it as "Initial commit", or maybe it is meant for an older/newer php version than the one I have.

**Comment by Findus23** [comment]
While I honestly have no idea how this can happen, I think with the change in https://github.com/Findus23/plugin-ProfileAvatar/commit/505ca2f057a4c98127215e96d47b197ffac964b9 (or 0.1.4) it should not happen anymore.

**Comment by Tc-001** [comment]
Thanks, that seems to have fixed it.
